Repository revanced/revanced-cli, pull requests merged in 2022-07, with the labels that each got.

#77 feat: better output for excluded patches
  src/main/kotlin/app/revanced/utils/patcher/Patcher.kt
Labels: change-required

#78 feat: `--exclusive` switch
  src/main/kotlin/app/revanced/cli/command/MainCommand.kt
  src/main/kotlin/app/revanced/cli/patcher/Patcher.kt
  src/main/kotlin/app/revanced/utils/patcher/Patcher.kt
Labels: feature-request

#84 feat: `--uninstall` switch & move unmount script to command
  src/main/kotlin/app/revanced/cli/command/MainCommand.kt
  src/main/kotlin/app/revanced/cli/patcher/Patcher.kt
  src/main/kotlin/app/revanced/cli/signing/Signing.kt
  src/main/kotlin/app/revanced/utils/adb/Adb.kt
  src/main/kotlin/app/revanced/utils/adb/Constants.kt
  src/main/kotlin/app/revanced/utils/patcher/Patcher.kt
Labels: feature-request

#85 fix: dont crash on a null when resource patching is disabled
  src/main/kotlin/app/revanced/cli/patcher/Patcher.kt
Labels: bug

#80 fix: Log not showing in CLI
  src/main/kotlin/app/revanced/cli/logging/impl/DefaultCliLogger.kt
  src/main/kotlin/app/revanced/cli/logging/impl/FlushingStreamHandler.kt
  src/main/kotlin/app/revanced/cli/patcher/logging/impl/PatcherLogger.kt
Labels: bug
